gaussian_ply_path: null
output_dir: output/gaussians
output_ply_name: optimized.ply
debug_dir_name: debug
device: cuda
lr: 0.005
phase_settings:
  phase1:
    steps: 7999
    cam_count: 6
    jitter_views_per_cam: 4
    fixer_view_use_ratio: 0.1
    minscale_loss:
      weight: 0.5
      min_scale: 0.001
      max_scale: 0.05
      min_weight: 0.1
      max_weight: 6000.0
    scale_ratio_loss:
      weight: 0.01
      max_ratio: 2.0
      gamma: 0.001
    opacity_sparsity_loss:
      weight: 0.002
    photometric_loss:
      weight: 1.5
    jitter_cm: 0.2
  phase2:
    steps: 1000
    cam_count: 6
    jitter_views_per_cam: 4
    fixer_view_use_ratio: 0.33
    photometric_loss:
      weight: 1.0
    fixer_loss:
      weight: 0.02
      low_freq_weight: 1.0
      lpips_weight: 0.1
      use_lpips: true
      lpips_net: vgg
      danger_percentile: 0.25
      blur_sigma: 1.5
      gamma: 5.0
    jitter_cm: 50.0
  phase3:
    steps: 1000
    cam_count: 6
    jitter_views_per_cam: 4
    fixer_view_use_ratio: 0.33
    photometric_loss:
      weight: 1.0
    fixer_loss:
      weight: 0.02
      low_freq_weight: 1.0
      lpips_weight: 0.1
      use_lpips: true
      lpips_net: vgg
      danger_percentile: 0.25
      blur_sigma: 1.5
      gamma: 5.0
    jitter_cm: 100.0
merge:
  every: 2000
  voxel_size: 0.002
  voxel_size_distance_scale: 0.06
  small_scale: 0.01
  prune_scale: null
  prune_thin_opacity: 0.04
  color_bin: 0.005
background_freeze_steps: null
background_remove_step: null
log_every: 50
sky_mask:
  erode_kernel: 3
  erode_iter: 1
  sam3_prompt: sky
  sam3_invert: true
  sam3_model_id: facebook/sam3
  sam3_device: cuda
  sam3_dtype: auto
  sam3_mask_threshold: 0.5
  sam3_resize_longest_side: null
background_color:
  - 1.0
  - 1.0
  - 1.0
random_seed: 0
