prompt: "sunset urban street, cinematic"
config_file: "configs/nuscenes/main.yaml"
output_dir: "output"
novel_view_mode: "MF"
sample_index: 0
height: null
blend_width: 0
model_id: "stabilityai/stable-diffusion-xl-base-1.0"
# controlnet_id: "diffusers/controlnet-depth-sdxl-1.0"
controlnet_id: diffusers/controlnet-canny-sdxl-1.0
depth_model_id: "depth-anything/DA3METRIC-LARGE"
depth_device: "cuda"
strength: 0.6
steps: 30
guidance_scale: 5.0
controlnet_scale: 1.0
cpu_offload: false
sequential_offload: false
xformers: false
seed: null
